### ISSUE TITLE
PacketProcessor

### ISSUE THREAD

**Issue by RajanGrewal** [dangoron/MapleStory#1]
Hi , I am one of the guys who originally wrote the base you are using.  In packet processor this line:

            _handlers = new PacketHandler[0xFFFF];

will kill memory for no reason, Its better to use a dictionary. 

Also in your Client.cs the receive methods may not return the full length , you should go back to the append and manipulate buffer methods i had there before. Also async methods are slower than the original way I had it before with the Begin..End patterns

Also for IO using binary writer / reader is slow, you should just do everything manually with a byte array.

Cheers.  If you have any more questions feel free to ask.

**Comment by dangoron** [comment]
Hi, RajanGrewal.
Thanks for your comment. You are right, I also noticed that problem, so I wrote a comment "maybe it's better to use dictionary" there (in Chinese though XD).
I will try to make this project better, cause I have many parts to finish, currently XmlToBin is finished somehow (not all data is well managed though). Next I will make some changes on the network part.
Anyway, thank you for the noice.
And it is general rule to add credits to those made contribution to the codes. Because this project is very primary and I have to build it for long. So maybe I will add all the credits at the end.
Best :)

**Comment by RajanGrewal** [comment]
Awesome glad to hear you are further developing it !

BTW here are some better PacketReader/Writers from another old project

https://github.com/LankMasterFlex/RajanMS/blob/master/RajanMS/RajanMS/Core/IO/OutPacket.cs
https://github.com/LankMasterFlex/RajanMS/blob/master/RajanMS/RajanMS/Core/IO/InPacket.cs
https://github.com/LankMasterFlex/RajanMS/blob/master/RajanMS/RajanMS/Core/IO/BufferPool.cs

If you have any questions or looking for suggestions give me a shout !

**Comment by dangoron** [comment]
I'll take these codes into consideration. Thank you for the suggestions!
